### ISSUE TITLE
Missing Animation Trigger

### ISSUE THREAD

**Issue by Sohail05** [DRUID002/resumeWebsite#2]
You are using pure CSS for animation.

You have to include a `:` with a property like `hover`.

```
#menu:active{
  background: $grey;
  position: fixed;
  width: 100%;
  top: 0;
  bottom: 0;
  position: translate3d(-100%, 0, 0);
  z-index: 10;
  display: flex;
  align-items: center;
  justify-content: center;
  opacity: 1;
  transition: all 0.5s ease-in-out;
```

**Comment by Sohail05** [comment]
You can use JS to add the class to the target element which will then trigger the animation.

**Comment by DRUID002** [comment]
Okay going to try that

**Comment by ScorpioCoding** [comment]
I've done some work for you, all you have to do is merge the pull request.
https://github.com/ScorpioCoding/resumeWebsite

**Comment by DRUID002** [comment]
wow omg bro, I literally cannot think you enough. You’ve helped me out a lot! I got no help being a noob developer. But i may ask….why did you help me out so much ? Do you want something in return ?
Darion S.
darionsuggs@icloud.com

**Comment by DRUID002** [comment]
Hey whats your facebook?
Darion S.
darionsuggs@icloud.com

**Comment by ScorpioCoding** [comment]
1. Help you out cause I felt like it and no do not need anything in return, other the the return in gesture.
-- pay it forward dude --
2. I saw that your work needed guidance so I offered, you don't have to accept (merge my pull request)
-- I see you need more than just basics in html , css and js
-- I see also that you need help with fiel structure, Npm, Github (Gitignore, Readme, Issues, Wiki, etc)
-- I see you need help with preprocessor Node-sass and Sass
-- But most of all I see that you need design/ Development sequence/ structure / process order
-- -- Like starting with Thinking about your project, who is your audience?
-- -- like researching your audience and what they like and dislike of profile sites
-- -- Research your audiences UX/UI
-- -- Find your identity, color scheme, moodboard  / storyboard , logo , your branding, what are your values?
-- -- Start by sketching on paper, then wireframe, then prototype and mock-up
-- --Then ask how am I going to develop my site which technologies?
-- -- -- plain old vanilla html css js
-- -- -- html5 jQuery Sass (with or without a frontend package)
-- -- --php Sass jQuery MySql (with or without a backend package)
3. What ever you do make shore you do mock-up preferly in photoshop and put your psd in a folder within your dev project and upload it to github. So that people can help you acheave your vision.
-- I always create a proj/ folder and I chuck all sorts of things in there
-- -- Cheatshets.md, Guids.md, Readmes.md, mock-up.psd, mock-up.png (github wiki) etc. etc.

But hey your learning cool keep at it dude.
And don't feel crushed by the stack of info I just bombshelled you with.  
Just remember one thing: "Rome wasn't build in a Day"
So don't get stressed about it all just get fing good in organizing your stuff:
-- -- code snippets -> jsFiddle or Codepen
-- -- your demo's and templates and samples -> github or bitbucket
-- -- create a project folder and in that folder create a pub (release) and a dev folder.
-- -- -- create 2 github repo's if it's your intention to publish to github pages.

DO NOT stack on icons or images videos if they are not yours or you are not using them for a project.
You can find images everywhere just google or pexel.com

And if your a logo, icon, image creator then publish your work, Dribble, Behance envator..
these are cool places to look for inspiration for your moodboard.

So there you are a career in design and development in a nutshell

need more help give a shout

**Comment by ScorpioCoding** [comment]
sorry for the book I wrote..lol

**Comment by ScorpioCoding** [comment]
SO yeah that Fb thing .. seriously haven't logged in for months.
But you can find me mostly under my handle `ScorpioCoding` 
[Website](https://scorpiocoding.net) [Facebook](https://www.facebook.com/ScorpioCoding/) [Twitter](https://twitter.com/ScorpioCoding)

Those are the basic I think there also redit, behance, dribble, codepen, fiddle, codeproject, Medium, SensioLabs, Stackoverflow and lots more

**Comment by DRUID002** [comment]
Are you into Mentoring ?
